### PR TITLE
fix tokenize_row in XXPOTrainer

### PR DESCRIPTION
**Pull request by AIR-hl**
- Remove `tokenize_row` and `build_tokenized_answer` from `DPOTrainer.py`, `ORPOTrainer.py` and `CPOTrainer.py`;
- Add `tokenize_row` and `build_tokenized_answer` to `trainer/utils.py`;
- Modify the codes related to the function in the corresponding files;
- Modify the parameter `max_completion_length` to `max_target_length` in `ORPO` in order to be consistent with `DPO` and `CPO`

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for this great clean up ! 
Can you just run the styling checks? `make precommit` ?

**Comment by younesbelkada** [comment]
After that you should commit & push the changed files

**Comment by younesbelkada** [comment]
```bash
make precommit
git add -u 
git commit -m"styling checks"
git push
```

**Comment by AIR-hl** [comment]
> ```shell
> make precommit
> git add -u 
> git commit -m"styling checks"
> git push
> ```

done

**Comment by younesbelkada** [comment]
Hmm it seems a bad rebase happened (see the number of changed files), can you re-open a new PR by fetching the latest commit from main?

**Pull request closed without merging**
