### PR TITLE
Support num_train_epochs

### PR DESCRIPTION
**Pull request by vwxyzjn**
Closes https://github.com/huggingface/trl/issues/1740

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks ! the CLI tests seem to fail, can you have a look? Also make sure to merge your branch with main to make sure the CI runs with the correct numpy version

**Comment by vwxyzjn** [comment]
Yeah I think it's the numpy issue. Merging main and trying again.

**Review by younesbelkada — APPROVED** [review]

**Review by younesbelkada — APPROVED** [review]
Thanks ! Can you merge again with main to see if the failing tests now pass ?

**Review by younesbelkada — COMMENTED** [review]
Thanks ! I think we should make `push_to_hub` modulable and default it to False to make the CI happy

**Comment by vwxyzjn** [comment]
Alright CI finally passed. The failing one was because hf.co timeout. Everything looks good. Merging now.

**Pull request merged**
