### PR TITLE
SDXL support for DDPO 

### PR DESCRIPTION
**Pull request by kabachuha**
Should work, but need to test myself on an A100

### CODE REVIEW

**Comment by younesbelkada** [comment]
Great work @kabachuha ! Let us know when this is ready for review, cc @sayakpaul

**Comment by kabachuha** [comment]
It's ready, just need to spend a bit time to rent an A100 and make a test, maybe not with the aesthetic model, but with jpeg compressibility instead (aesthetic model's resolution is too low for sdxl)

**Comment by kabachuha** [comment]
@younesbelkada this would be great! <3

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot! I just ran `python ddpo_sdxl_compressibility.py` and got:

```bash
, line 443, in check_inputs
    raise ValueError(f"`height` and `width` have to be divisible by 8 but are {height} and {width}.")
ValueError: `height` and `width` have to be divisible by 8 but are 1024 and 1.
```
Can you help guide me how to successfully run the script?

**Comment by kabachuha** [comment]
Oops, forgot about the sdxl dims setting for the script 👀

Anyway, when I come home (in ~6 hours), I'm going to make a small run on remote to ensure that it fully works (with pipeline calls and rl cycles) and report back

**Comment by younesbelkada** [comment]
Awesome thank you very much @kabachuha !

**Comment by kabachuha** [comment]
The cloud has really bad internet today 😩. Still, I think I put the right params into the places in the last commit. Would it be possible for you @younesbelkada to test it again?

**Comment by younesbelkada** [comment]
OK thanks @kabachuha ! let me know how it goes!

**Comment by kabachuha** [comment]
Almost made it work (pipeline, parameters transfer). The only remaining part is the loss calculation. Hopefully, will be ready this weekend

**Comment by kabachuha** [comment]
It kinda works, but there's the `Trying to backward through the graph a second time` error in the loss calculation function, need to think about it

**Comment by kabachuha** [comment]
Well, it works with `retain_graph=True` in the trainer, but it OOMs even on a A100, so idk how to test it

**Comment by AmericanPresidentJimmyCarter** [comment]
This should really be unet and text encoder agnostic. It's as relevent for SD 1.x and 2.x as it is for SDXL.

**Comment by anonymous-atom** [comment]
Hey @kabachuha any updates about your script ? Does it works ? I want to try it with some loss function.

**Comment by anonymous-atom** [comment]
Hi @kabachuha , I also tried to test the code from your ddpo-sdxl form. I ran the ddpo_sdxl_compressibilty.py file and it's using DefaultDDPOStableDiffusionPipeline instead of the XL DDPO pepeline you implemented.

**Pull request closed without merging**
