### PR TITLE
Fix unwrapping peft models

### PR DESCRIPTION
**Pull request by kkteru**
Fixes issues discussed [here](https://github.com/huggingface/transformers/pull/27162#discussion_r1380707614).

cc @younesbelkada

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Makes sense, thanks!

**Comment by younesbelkada** [comment]
Hi @kkteru 
Can you merge this branch with main branch to make sure tests pass?

**Comment by kkteru** [comment]
Interesting, somehow the test_sft_trainer.py tests failed on latest main branch (without any changes from this branch) in my local. Investigating further.

**Comment by younesbelkada** [comment]
@kkteru what are the failed tests? might be unrelated to your changes I think - you can just merge your branch with upstream main and see here if the tests pass

**Comment by kkteru** [comment]
These ones fail both on the main branch and this branch (merged with main) on my system. I just rebased on top of latest main and pushed. I dont see the tests running here?

```
=================================================================== short test summary info ====================================================================
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer - AssertionError: False is not true
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer_infinite_with_model - AssertionError: False is not true
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer_infinite_with_model_epochs - AssertionError: False is not true
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer_with_model - AssertionError: False is not true
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer_with_model_num_train_epochs - AssertionError: False is not true
```

**Comment by younesbelkada** [comment]
The tests were failing because you had an old version of transformers, installing the 4.35.0 will fix your isses! As you can see, CI is green now :D

**Review by younesbelkada — APPROVED** [review]
Awesome clean up !

**Pull request merged**
