### PR TITLE
Integrate f-divergence to DPO (Follow up)

### PR DESCRIPTION
**Pull request by 1485840691**
Updated based on previous PR: https://github.com/huggingface/trl/pull/1339

Main actions: solve conflicts and merge the dev branch with main branch

### CODE REVIEW

**Comment by younesbelkada** [comment]
Is this PR still a WIP ? @1485840691 
cc @kashif

**Comment by 1485840691** [comment]
> Is this PR still a WIP ? @1485840691 cc @kashif

Yes, but it is almost done. I am trying to fix any errors encountered during the build. Then wait for any reviews on the code.

**Review by kashif — APPROVED** [review]

**Comment by 1485840691** [comment]
Thanks for the review. Please inform me if there is anything to do from my side. If everything is OK,  please help merge the repo to the main branch. Thanks
@kashif @younesbelkada

**Comment by qgallouedec** [comment]
`evaluation_strategy` is deprecated, replaced by `eval_strategy`. Fix here: #1771

**Pull request merged**
