### PR TITLE
updating PPOTrainer docstring

### PR DESCRIPTION
**Pull request by lomahony**
adding specific dict structure to tracker_kwargs doc string to enable changing tracker params like wandb experiment name for ease, avoids needing to go deep into accelerate source

### CODE REVIEW

**Review by lvwerra — APPROVED** [review]
Looks good to me, thanks! maybe @vwxyzjn wants to have a quick look too!

**Comment by vwxyzjn** [comment]
Running into some minor issues at https://github.com/brentyi/tyro/issues/79 but should be resolved soon.

**Comment by vwxyzjn** [comment]
Now we can be run it with `python examples/scripts/ppo.py --ppo_config.tracker_kwargs='{"wandb": {"entity": "vwxyzjn", "name": "haha"}}' --ppo_config.log_with=wandb`

**Comment by lomahony** [comment]
Thanks very much all! The library is excellent and very user-friendly 💯

**Pull request merged**
