### PR TITLE
Add WinRateCallback and Judges

### PR DESCRIPTION
**Pull request by lewtun**
Command for testing:

```shell
TRANSFORMERS_VERBOSITY=info ACCELERATE_LOG_LEVEL=info TRL_USE_RICH=true accelerate launch --config_file=examples/accelerate_configs/multi_gpu.yaml --num_processes=8 examples/scripts/dpo_online.py     --dataset_name=trl-internal-testing/hh-rlhf-helpful-base-trl-style     --dataset_num_proc=4     --model_name_or_path=Qwen/Qwen1.5-0.5B-Chat     --per_device_train_batch_size 4     --learning_rate 5e-7     --gradient_accumulation_steps 1     --logging_steps 10    --evaluation_strategy=steps  --eval_steps 10 --num_train_epochs=6     --output_dir="scratch/dpo_anthropic_hh"     --warmup_steps 150     --report_to wandb     --bf16     --logging_first_step     --no_remove_unused_columns --sanity_check
```

## TODO

- [x] Implement batched generation
- [x] Add judge for HF inference API
- [x] Add tests
- [x] Add docs
- [ ] Add sampling params for judge LLM

### CODE REVIEW

**Comment by qgallouedec** [comment]
```python
import tempfile
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from trl import DPOConfig, DPOTrainer, WinRateCallback, MockJudge


def init_dataset():
    # fmt: off
    dummy_dataset_dict = {
        "prompt": [
            "Hello, nice",
            "How are",
            "The capital of France is",
            "The best programming",
            "USER: Where can I find the documentation for Python?",
        ],
        "chosen": [
            " to meet you.",
            " you doing?",
            " Paris.",
            " language is Python.",
            " ASSISTANT: You can find it for Python at https://docs.python.org/3/.",
        ],
        "rejected": [
            " to run.",
            " you zooming?",
            " Lyon.",
            " language is Java.",
            " ASSISTANT: You can find it for Python at https://docs.oracle.com/en/java/.",
        ],
    }
    # fmt: on
    return Dataset.from_dict(dummy_dataset_dict)


with tempfile.TemporaryDirectory() as tmp_dir:
    training_args = DPOConfig(
        output_dir=tmp_dir,
        per_device_train_batch_size=2,
        max_steps=3,
        remove_unused_columns=False,
        eval_strategy="steps",
        logging_steps=1,
    )

    dataset = init_dataset()
    model_id = "trl-internal-testing/dummy-GPT2-correct-vocab"
    model = AutoModelForCausalLM.from_pretrained(model_id)
    ref_model = AutoModelForCausalLM.from_pretrained(model_id)
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    tokenizer.pad_token = tokenizer.eos_token

    trainer = DPOTrainer(
        model=model,
        ref_model=ref_model,
        args=training_args,
        tokenizer=tokenizer,
        train_dataset=dataset,
        eval_dataset=dataset,
    )

    win_rate_callback = WinRateCallback(prompts=dataset["prompt"], judge=MockJudge(), trainer=trainer)
    trainer.add_callback(win_rate_callback)
    trainer.train()
```

**Comment by qgallouedec** [comment]
- [ ] Add callback to the doc

**Comment by qgallouedec** [comment]
The document won't upload. This seems to be a temporary problem with the doc builder (not related to this pr.).

**Review by kashif — APPROVED** [review]

**Comment by qgallouedec** [comment]
For some reason, HfJudge prefers "The capital of France is Berlin"

**Pull request merged**
