### PR TITLE
adds AOT

### PR DESCRIPTION
**Pull request by imelnyk**
This code adds Distributional Preference Alignment Via Optimal Transport (AOT) to TRL. 

`self.loss_type == "aot"` - this part is for the cases where for each prompt there is a pair of chosen and rejected responses.

`self.loss_type == "aot_pair"` - here for each prompt the chosen and rejected responses do not need to be paired (e.g., as in kto_pair)

Note that for AOT algorithm to really show its advantage, the actual per-GPU batch size needs to be maximized. 

In our upcoming ArXiv paper we show that, for example, _ibm/merlinite-7b_ (original AlpacaEval LC Win Rate 17.1) can be aligned using our AOT method to get to _ibm/merlinite-7b-AOT_ with AlpacaEval LC Win Rate 31.3

### CODE REVIEW

**Comment by kashif** [comment]
thanks @imelnyk can you also kindly add a description of the method and how to use it in the trainer's doc as well as have the tests also run with this loss?

**Review by younesbelkada — COMMENTED** [review]
Great contribution @imelnyk ! As stated by @kashif can you add few lines in the documentation about this new method?

**Comment by imelnyk** [comment]
Thanks for the reminder, @younesbelkada @kashif. Yes, we are working on it now and we'll update this PR soon. Thank you!

**Comment by imelnyk** [comment]
@younesbelkada @kashif : I pushed the changes (docs + tests)

**Review by younesbelkada — APPROVED** [review]
Great contribution ! Thanks a lot for adding this !

**Review by kashif — APPROVED** [review]

**Pull request merged**
