### PR TITLE
[`DPOTrainer`] Load data only on main process + fix dpo example test

### PR DESCRIPTION
**Pull request by younesbelkada**
Adds the simple fix proposed in https://github.com/huggingface/trl/pull/1255 to speed up data processing for DPO + multi GPU + fixes the example test that I made it fail after https://github.com/huggingface/trl/pull/1289 

cc @kashif

### CODE REVIEW

**Review by kashif — APPROVED** [review]

**Comment by kashif** [comment]
thank you!

**Comment by esceptico** [comment]
Hey there! Thanks for the PR.
Should we also add num_proc arg to the eval_dataset processing?

**Comment by kashif** [comment]
yes @esceptico  would you like to send a pr?

**Comment by esceptico** [comment]
Sure!
I'll send a PR tomorrow.

**Pull request merged**
