### PR TITLE
Add Error Handling for Stale Issue Script in GitHub Action

### PR DESCRIPTION
**Pull request by Ananya54321**
# What does this PR do?
This PR adds comprehensive error handling to the script responsible for closing stale issues in the repository. The main updates include:

**Error handling for missing GitHub token**: Ensures the GITHUB_TOKEN environment variable is set and valid.
**Error handling for GitHub API operations**: Wrapped all GitHub API operations (issue retrieval, comments, etc.) in try-catch blocks to gracefully handle API failures.
**Rate Limit Handling**: Catches and logs GitHub API rate limit errors (RateLimitExceededException), allowing the script to pause if needed.
**General error handling**: Added safeguards to catch and report unexpected errors during script execution.
These changes make the script more robust and ensure it handles any issues gracefully without crashing.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a GitHub issue? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by qgallouedec** [comment]
Thanks for the PR! However, I was actually considering simply removing this bot. In my opinion, it's fine to leave issues open for extended periods. I generally review all the issues and follow up when more information is needed and there hasn't been any activity for a while. From my experience, this bot tends to close issues that should remain open more often than it helps track active ones. See #1949 #1956.
What's more, the bot doesn't seem to have been working for a while, and nobody here seems to miss it.
What do you think @lewtun @kashif?

**Comment by Ananya54321** [comment]
Ohh that makes sense! Thank you for responding!

**Comment by lewtun** [comment]
Yes I agree, let's disable the bot since it's more of a nuisance than a help

**Comment by qgallouedec** [comment]
Close as a consequence of #2300

**Pull request closed without merging**
