### PR TITLE
Fix issue with precompute_ref_log_probs not working when rpo_alpha is None

### PR DESCRIPTION
**Pull request by mina-parham**
When using the `precompute_ref_log_probs=True` option, the training process is halted( the training loss sucks at 0.6932 which shows the model is not training). This issue arises due to the following code segment:

```
if (
            "reference_chosen_logps" in batch
            and "reference_rejected_logps" in batch
            and self.args.rpo_alpha is not None
        ):
            reference_chosen_logps = batch["reference_chosen_logps"]
            reference_rejected_logps = batch["reference_rejected_logps"]
```

The condition `self.args.rpo_alpha` is not None prevents the `reference_chosen_logps` and `reference_rejected_logps` from being used in the training process when `rpo_alpha` is set to None. This is problematic because when `precompute_ref_log_probs=True`, we still need to access these log probabilities from the batch regardless of the `rpo_alpha` value.

To resolve this issue, the condition should be adjusted to ensure that `reference_chosen_logps` and `reference_rejected_logps` are accessed when `precompute_ref_log_probs` is set to True, independent of the `rpo_alpha` value.

### CODE REVIEW

**Review by kashif — APPROVED** [review]
good catch

**Comment by kashif** [comment]
@mina-parham would it be possible to add a test for this?

**Comment by mina-parham** [comment]
> @mina-parham would it be possible to add a test for this?

yes of course, I'm on it :-)

**Comment by mina-parham** [comment]
I added the test for this.

**Pull request merged**
