### PR TITLE
fix: unpackaging error in Custom Mixture of Experts model when `aux_loss_enabled` is set to True.

### PR DESCRIPTION
**Pull request by Jonathanjordan21**
# What does this PR do?

This PR fixes https://github.com/huggingface/trl/issues/2038.

Fix unpackaging error due to additional `aux_loss` returned by `concatenated_forward` function when `aux_loss_enabled=True`.

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a GitHub issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kashif** [comment]
thanks @Jonathanjordan21 

perhaps its more ellegant to do:

```py
reference_chosen_logps, reference_rejected_logps = self.concatenated_forward(self.ref_model, padded_batch)[:2]
```

what do you think?

**Comment by Jonathanjordan21** [comment]
@kashif seems good. I actually just followed the earlier code which calculate the policy losses in `get_batch_loss_metrics` function. 

```python
1440        forward_output = self.concatenated_forward(model, batch)
1441        (
1442            policy_chosen_logps,
1443            policy_rejected_logps,
1444            policy_chosen_logits,
1445            policy_rejected_logits,
1446            policy_nll_loss,
1447       ) = forward_output[:5]
1448       if self.aux_loss_enabled:
1449            aux_loss = forward_output[5]
```

**Comment by kashif** [comment]
yeah... i should have just done the above but happy if you do it!

**Comment by kashif** [comment]
you might need to run `pre-commit run --all-files` in the root of the TRL folder fix any formatting issues

**Review by kashif — APPROVED** [review]

**Pull request merged**
