### PR TITLE
Issue #1751 Fix

### LINKED ISSUE #1751: [BUG] TRL CLI not capturing `torch_dtype` correctly
## Description

Hi here! 🤗 Apparently the TRL's CLI command `trl sft` is not properly capturing the value provided to the `--torch_dtype` flag as it does not identify it as a string when calling `getattr(torch, model_init_kwargs["torch_dtype"])`.

Most likely this issue happens on the rest of the implementations since when parsing the `torch_dtype` provided by the CLI the conversion to `torch.dtype` happens, and then the `SFTTrainer` in this case, receives the `torch_dtype=torch.bfloat16` instead, and attempts to `getattr(torch, torch.bfloat16)`.

So there's two potential fixes:

* Handling the received type for `torch_dtype` within each `...Trainer` subclass so as to provide it to the `model_init_kwargs` as it without the need of calling `getattr(torch, ...)`
* Respecting the `torch_dtype` as a string and letting each `...Trainer` subclass do the `str` -> `torch.dtype` conversion instead, which is more convenient IMO

## To reproduce

```bash
trl sft --model_name_or_path=facebook/opt-125m --dataset_name=imdb  --dataset_text_field=text --max_steps=1 --torch_dtype=bfloat16 --output_dir=./test
```

### PR DESCRIPTION
**Pull request by yash-srivastava19**
#1751 mentioned that the TRL CLI is not completely capturing the torch_dtype. I thought the issue was urgent, so quickly patched a hacky fix, which at least initiates the SFT Trainer. 

Original Issue : 
On running the following command :
```
trl sft --model_name_or_path=facebook/opt-125m --dataset_name=imdb  --dataset_text_field=text --max_steps=1 --torch_dtype=bfloat16 --output_dir=./test
```
The error was that trl sft is does not identify it as a string when calling `getattr(torch, model_init_kwargs["torch_dtype"])`.

The fix was made which allows the to not break the pipeline at this stage. Although it is a hacky fix, I'm willing to work on it further :)

The error after that is from the transformers library that isn't able to serialize the dtype object(screenshot attached):

```
...
...
TypeError: Object of type dtype is not JSON serializable
Traceback (most recent call last):
```   

Screenshot 2024-06-18 171826

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for this ! I second what @alvarobartt said above, we can change this fix to something like:

```diff
diff --git a/trl/trainer/sft_trainer.py b/trl/trainer/sft_trainer.py
index e739b2d..80e11ad 100644
--- a/trl/trainer/sft_trainer.py
+++ b/trl/trainer/sft_trainer.py
@@ -159,11 +159,13 @@ class SFTTrainer(Trainer):
             raise ValueError("You passed model_init_kwargs to the SFTConfig, but your model is already instantiated.")
         else:
             model_init_kwargs = args.model_init_kwargs
-            model_init_kwargs["torch_dtype"] = (
-                model_init_kwargs["torch_dtype"]
-                if model_init_kwargs["torch_dtype"] in ["auto", None]
-                else getattr(torch, model_init_kwargs["torch_dtype"])
-            )
+            torch_dtype = model_init_kwargs["torch_dtype"]
+
+            # Convert to `torch.dtype` if an str is passed
+            if isinstance(torch_dtype, str) and torch_dtype != "auto":
+                torch_dtype = getattr(torch, torch_dtype)
+
+            model_init_kwargs["torch_dtype"] = torch_dtype

         if infinite is not None:
             warnings.warn(
```
And it worked fine on my end! Would you be happy to apply these changes instead in this PR?

**Comment by yash-srivastava19** [comment]
> Thanks a lot for this ! I second what @alvarobartt said above, we can change this fix to something like:
> 
> ```diff
> diff --git a/trl/trainer/sft_trainer.py b/trl/trainer/sft_trainer.py
> index e739b2d..80e11ad 100644
> --- a/trl/trainer/sft_trainer.py
> +++ b/trl/trainer/sft_trainer.py
> @@ -159,11 +159,13 @@ class SFTTrainer(Trainer):
>              raise ValueError("You passed model_init_kwargs to the SFTConfig, but your model is already instantiated.")
>          else:
>              model_init_kwargs = args.model_init_kwargs
> -            model_init_kwargs["torch_dtype"] = (
> -                model_init_kwargs["torch_dtype"]
> -                if model_init_kwargs["torch_dtype"] in ["auto", None]
> -                else getattr(torch, model_init_kwargs["torch_dtype"])
> -            )
> +            torch_dtype = model_init_kwargs["torch_dtype"]
> +
> +            # Convert to `torch.dtype` if an str is passed
> +            if isinstance(torch_dtype, str) and torch_dtype != "auto":
> +                torch_dtype = getattr(torch, torch_dtype)
> +
> +            model_init_kwargs["torch_dtype"] = torch_dtype
> 
>          if infinite is not None:
>              warnings.warn(
> ```
> 
> And it worked fine on my end! Would you be happy to apply these changes instead in this PR?

Yes, it is much more optimal. Agreed

**Comment by yash-srivastava19** [comment]
Did the json encoding error rectified as well or it pertains even after the fix?

**Comment by younesbelkada** [comment]
Thanks ! that's another issue we can fix in a follow up PR !

**Comment by alvarobartt** [comment]
Hi here @yash-srivastava19 friendly ping to check about the status of this PR 👍🏻 Is it something you are still happy / comfortable to work with? Or would you prefer us to take over instead? Just let us know, thanks 🤗

**Comment by alvarobartt** [comment]
Hi here @yash-srivastava19 thanks for the effort, we'll be closing this PR in favour of https://github.com/huggingface/trl/pull/1807, and you've been included as a contributor there 🤗 Thanks a lot for the effort!

**Pull request closed without merging**
