### PR TITLE
fix stackllama2 sft gradient checkpointing

### PR DESCRIPTION
**Pull request by nrailg**

### CODE REVIEW

**Review by vwxyzjn — CHANGES_REQUESTED** [review]
@nrailg thanks for this PR. We have since elected to use `tyro` to reduce duplications in argparse. Would you mind modifying the PR to adhere to the style in https://github.com/huggingface/trl/blob/1f3314fd2f2e1286e64cb8fac9afb58244b07700/examples/scripts/reward_modeling.py#L32-L73?

I imagine you can do something like 

```
@dataclass
class ScriptArguments:
    model_name: str = "facebook/opt-350m"
    """the model name"""
    sft_config: TrainingArguments = field(
        default_factory=lambda: TrainingArguments(
            ...
            gradient_checkpointing=True,
        )
    )
```

**Comment by nrailg** [comment]
> @nrailg thanks for this PR. We have since elected to use `tyro` to reduce duplications in argparse. Would you mind modifying the PR to adhere to the style in
> 
> https://github.com/huggingface/trl/blob/1f3314fd2f2e1286e64cb8fac9afb58244b07700/examples/scripts/reward_modeling.py#L32-L73
> 
> ?
> I imagine you can do something like
> 
> ```
> @dataclass
> class ScriptArguments:
>     model_name: str = "facebook/opt-350m"
>     """the model name"""
>     sft_config: TrainingArguments = field(
>         default_factory=lambda: TrainingArguments(
>             ...
>             gradient_checkpointing=True,
>         )
>     )
> ```

Upgraded.

**Comment by vwxyzjn** [comment]
@nrailg I have added a few more changes. Could you fix the test cases (run `make precommit` and possibly run a tracked experiment in wandb? `python sft_llama2.py`.

**Comment by nrailg** [comment]
> @nrailg I have added a few more changes. Could you fix the test cases (run `make precommit` and possibly run a tracked experiment in wandb? `python sft_llama2.py`.

I'll try it later.

**Comment by nrailg** [comment]
> @nrailg I have added a few more changes. Could you fix the test cases (run `make precommit` and possibly run a tracked experiment in wandb? `python sft_llama2.py`.

I made a `make precommit` and formatted the code.

I ran the code like this
```bash
accelerate launch sft_llama2.py --dataset_name /home/nrwu/work/hf-hub/lvwerra/stack-exchange-paired/ --model_name /home/nrwu/model-ckpt/Llama-2-7b-hf/ --training_args.per_device_train_batch_size 1 --training_args.per_device_eval_batch_size 1 --training_args.no_gradient_checkpointing
```

I found that gradient checkpointing doesn't work, so I disabled it. I guess it's caused by PEFT, for gradient checkpointing works well with deepspeed version of SFT (in my private repo).

**Comment by nrailg** [comment]
@vwxyzjn sorry I can not use WandB due to our weird GPU cluster limits.

But the loss curve looks OK to me.
image

**Review by vwxyzjn — APPROVED** [review]

**Comment by vwxyzjn** [comment]
Thanks so much for the PR.

**Comment by Elfsong** [comment]
@vwxyzjn Looks like 'tyro' doesn't work properly for 'TrainingArguments' now.

**Comment by vwxyzjn** [comment]
Hey @Elfsong sorry you are running this issue. This is prob due to https://github.com/huggingface/transformers/pull/27276 which is already fixed upstream and released. Could you try `pip install --upgrade transformers`?

**Comment by Elfsong** [comment]
> Hey @Elfsong sorry you are running this issue. This is prob due to [huggingface/transformers#27276](https://github.com/huggingface/transformers/pull/27276) which is already fixed upstream and released. Could you try `pip install --upgrade transformers`?

Hi @vwxyzjn It works now. Thank you!

**Comment by Elfsong** [comment]
> @nrailg thanks for this PR. We have since elected to use `tyro` to reduce duplications in argparse. Would you mind modifying the PR to adhere to the style in
> 

@vwxyzjn Hi, your lib "tyro" throws these errors: 

  File "/home/nus_ids_user3/Projects/ultramarine/src/sft_train.py", line 71, in <module>
    script_args = tyro.cli(ScriptArguments)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_cli.py", line 374, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_parsers.py", line 110, in from_callable_or_type
    field_out = handle_field(
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_parsers.py", line 322, in handle_field
    if _fields.is_nested_type(field.type_or_callable, field.default):
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_unsafe_cache.py", line 33, in wrapped_f
    out = f(*args, **kwargs)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_fields.py", line 249, in is_nested_type
    _try_field_list_from_callable(typ, default_instance),
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_fields.py", line 412, in _try_field_list_from_callable
    return field_list_from_class(cls, default_instance)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_fields.py", line 559, in _field_list_from_dataclass
    for dc_field in filter(lambda field: field.init, _resolver.resolved_fields(cls)):
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_unsafe_cache.py", line 33, in wrapped_f
    out = f(*args, **kwargs)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/tyro/_resolver.py", line 97, in resolved_fields
    annotations = get_type_hints(cls, include_extras=True)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/site-packages/typing_extensions.py", line 1266, in get_type_hints
    hint = typing.get_type_hints(
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/typing.py", line 1459, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/mnt/dataDisk1/miniconda3/envs/mercury/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and '_LiteralGenericAlias'

**Pull request merged**
