### PR TITLE
Version should have `dev0` unless it is a release version

### PR DESCRIPTION
**Pull request by mishig25**
Version should have dev0 unless it is a release version

### CODE REVIEW

**Comment by lvwerra** [comment]
Thanks for adding. Could you also update it in `trl/__init__.py` for consistency?

**Comment by mishig25** [comment]
Did so !

**Review by lvwerra — APPROVED** [review]
Thank you ❤️

**Comment by mishig25** [comment]
@lvwerra please feel free to merge it 👍

**Pull request merged**
