### PR TITLE
Fix Padding Behaviour

### PR DESCRIPTION
**Pull request by nivibilla**
Hi @younesbelkada , just moving the PR from #1194 to here, I accidentally made my changes in main lol.

### CODE REVIEW

**Comment by younesbelkada** [comment]
hi @nivibilla 
Thanks for the PR! 
i discussed offline with @lvwerra abotut these changes, would it be possible to send over a small reproducer of the issue you are facing? Perhaps the fix could be on the collator side but I am not sure.

**Comment by nivibilla** [comment]
Hi Younes, the dataset I used was proprietary but I'll try get you a Colab with the issue

**Comment by younesbelkada** [comment]
Ok that would be great! 🙏

**Comment by nivibilla** [comment]
Hi, not sure what changed but I'm unable to reproduce the issue. Even on my old code with the dataset I originally got the issue with.

Here is the [colab](https://colab.research.google.com/drive/1sVRk84r1XzO_34sZRyZIqsZIENmZHDSd?usp=sharing) anyway. Main thing is to set the max_length to be > lengths of the samples in training. But it seems to work fine. Ive tested it with tinyllama on colab and tinymix(mixtral arch) personally. 

Im happy to close this pr since there seems to be no issue with the current code.

**Comment by younesbelkada** [comment]
Ok thanks for the further investigation ! Yes let's close it for now - happy to make sure  your other PR gets landed in TRL !

**Pull request closed without merging**
