### PR TITLE
Adds a Rejection Sampling Trainer and sentiment tuning example

### PR DESCRIPTION
**Pull request by edbeeching**
Still a draft PR as the following needs to be added:

- logging stats for timings of generation, forward, backward and opt steps
- Testing with encoder models
- validate the masking is done correctly on the loss
- configs renaming, currently I use a PPOConfig 
- the trainer uses an AutoModelWithValueHead. The value head is not needed as we are just doing text generation.
- results seem a bit too good to be true. perhaps validate in other settings

Tested in a 8 GPU 1 node setting:
https://wandb.ai/edbeeching/trl/runs/hq5sn0z2?workspace=user-edbeeching

Comparison to PPO sentiment tuning:
image

### CODE REVIEW

**Comment by lvwerra** [comment]
Idea looks really nice! I wonder if we should do the `best_of_n` outside `step` maybe with the [existing tools](https://github.com/lvwerra/trl/blob/main/trl/extras/best_of_n_sampler.py) and have a generic `IterativeSFTTrainer`? What do you think?

**Comment by lvwerra** [comment]
Hi @edbeeching, as mentioned in https://github.com/huggingface/trl/pull/704#issuecomment-1705001973 I think it would be a great solution to have an `IterativeSFTTrainer` that we can use for several of these use cases that require some steps between optimizations. We then could accomodate the specific implementations in an example script rather than having dedicated trainers for each one of them. What do you think?

**Comment by edbeeching** [comment]
Hey @lvwerra , ye I think this is a good idea. I have not had much bandwidth to look at this, but I will find some time later this week to take a look.

**Comment by RylanSchaeffer** [comment]
@lvwerra @edbeeching I'm interested in this Rejection Sampling Trainer (motivated by Llama 2 and Llama 3) and I'm not clear how this can be implemented in the Iterative Trainer.

Does the Iterative Trainer support this Rejection Sampling-styled training approach? If so, is there documentation or a tutorial that demonstrates this?

**Pull request closed without merging**
