### PR TITLE
[DPO] add 'bco_pair' loss_type

### PR DESCRIPTION
**Pull request by seanexp**
add Binary Classifier Optimization (BCO) loss function from https://arxiv.org/abs/2404.04656

Implemented bce loss and reward shift in the paper.

I will make separate PR for unpaired version of BCO after rebase and polishing.

### CODE REVIEW

**Comment by kashif** [comment]
thanks @seanexp  perhaps lets also add some description in the DPO docs too?

**Comment by seanexp** [comment]
@kashif 

Ah yes! I'll work on it.

**Comment by seanexp** [comment]
@kashif 

Just added BCO description. [5439c90](https://github.com/huggingface/trl/pull/1524/commits/5439c9091830fbce8506545a4ba159ee93a1c693)

**Review by kashif — APPROVED** [review]

**Review by younesbelkada — APPROVED** [review]
Thanks for this addition !

**Pull request merged**
