### PR TITLE
pre-commit: replace linters + formatters with Ruff; fix some issues

### PR DESCRIPTION
**Pull request by akx**
As discussed in #1297, this PR wires up `ruff` (it apparently had been partially configured in #690 but never enabled) and fixes some common issues.

### CODE REVIEW

**Comment by akx** [comment]
@younesbelkada rebased + added a commit to upgrade to the freshly released Ruff 0.2.0

**Review by younesbelkada — APPROVED** [review]
Thanks !

**Comment by younesbelkada** [comment]
@akx could you rebase with main one last time just to make sure main doesn't break after merging this?

**Comment by akx** [comment]
@younesbelkada Done – sorry, was just traveling (hello from Brussels!)

**Review by younesbelkada — APPROVED** [review]
Thanks again @akx !

**Pull request merged**
