### PR TITLE
populate SUPPORTED_COMMANDS cli

### LINKED ISSUE #2101: [CLI] Extend training support to all trainers
### Feature request

The CLI currently supports training models with SFT/DPO/KTO: https://github.com/huggingface/trl/blob/6859e048da601fec181997a324e7b351fc997a33/trl/commands/cli.py#L24

It would be good to extend this support to all trainers so that we have a consistent API and also learn which parts of our scripts need refactoring to support this usage.

This could be tackled in separate PRs to keep things lightweight, and I'll track here the trainers in terms of priority to add (based on Hub usage):

* [orpo](https://huggingface.co/docs/trl/orpo_trainer)
* [reward modelling](https://huggingface.co/docs/trl/reward_trainer)
* [ppo](https://huggingface.co/docs/trl/ppov2_trainer)
* [rloo](https://huggingface.co/docs/trl/rloo_trainer)
* [online dpo](https://huggingface.co/docs/trl/online_dpo_trainer)
* [gkd](https://huggingface.co/docs/trl/gkd_trainer)
* [cpo](https://huggingface.co/docs/trl/cpo_trainer)
* [bco](https://huggingface.co/docs/trl/bco_trainer)
* [xpo](https://huggingface.co/docs/trl/xpo_trainer)
* [nash-md](https://huggingface.co/docs/trl/nash_md_trainer)

### Motivation

It is somewhat annoying that one cannot train a model through the CLI as this is helpful for fast debugging / iterations.

### Your contribution

Happy to open PRs, but this could be a good first issue for new contributors!

### PR DESCRIPTION
**Pull request by grumpyp**
# What does this PR do?
This closed #2101

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a GitHub issue? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).
- [x] Did you write any new necessary tests?

## Who can review?
@lewtun 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by qgallouedec** [comment]
Thanks for contributing. I would suggest a simpler approach. Just modify 

https://github.com/huggingface/trl/blob/78249d9de46486a7fdb99c441ce0f52b9b0e1980/trl/commands/cli.py#L130-L142

into

```python
 def main(): 
     command_name = sys.argv[1] 

     if command_name == "chat": 
         chat() 
     elif command_name == "env": 
         print_env() 
    else:
        train(command_name)
```

It should be enough, what do you think?

**Comment by grumpyp** [comment]
> #2101
Hi @qgallouedec 

Thanks for the feedback! I see your point about simplifying the approach. My initial thought was to keep the existing structure to maintain clarity for users regarding supported commands.

I mean it could be done in that straight forward way but as a user I would not know what commands I could use.

To find out I'd actually have to dig into the code and see what's gonna be executed e.g. how `train` works.


Maybe I am overcomplicating things here. This is my first contribution so I don't know what kinda users (weather technical enough or not) are using `trl`. 


Either way, I will adjust the implementation based on what you think is best!

**Comment by qgallouedec** [comment]
As a user I'd use

```
trl --help
```

We're currently tweaking `sys.argv` instead of a proper argparse. That's why the above command won't give anything.
But in the future, I'd like to use argparse instead.

**Comment by grumpyp** [comment]
@lewtun anything to say here maybe? You opened the issue and might have some additional suggestion.

Either way, I am happy to go with your suggestion. Please let me know how you'd want it.

**Comment by qgallouedec** [comment]
> `trl --help` wouldn't work and is currently also not working

In the future, we will probably move to subparser for the trl cli, so `trl --help` will output something.

> Either way, I am happy to go with your suggestion. Please let me know how you'd want it.

Do you mind trying with the above suggestion? Also, the critical point here is to add the tests: like this one

https://github.com/huggingface/trl/blob/78249d9de46486a7fdb99c441ce0f52b9b0e1980/tests/test_cli.py#L20-L28

**Comment by grumpyp** [comment]
> > `trl --help` wouldn't work and is currently also not working
> 
> In the future, we will probably move to subparser for the trl cli, so `trl --help` will output something.
> 
> > Either way, I am happy to go with your suggestion. Please let me know how you'd want it.
> 
> Do you mind trying with the above suggestion? Also, the critical point here is to add the tests: like this one
> 
> https://github.com/huggingface/trl/blob/78249d9de46486a7fdb99c441ce0f52b9b0e1980/tests/test_cli.py#L20-L28

Hi,

do you want me to add a test for each model or some dynamic way?

So if I understand correctly, you want to use the test you just proposed and this approach:

```
 def main(): 
     command_name = sys.argv[1] 

     if command_name == "chat": 
         chat() 
     elif command_name == "env": 
         print_env() 
    else:
        train(command_name)
 ```
 ?

**Comment by qgallouedec** [comment]
> do you want me to add a test for each model or some dynamic way?

For each model

**Comment by qgallouedec** [comment]
Closing as a consequence of CLI refactoring

**Pull request closed without merging**
