### PR TITLE
Codemod Unittest assertions to bare asserts

### PR DESCRIPTION
**Pull request by akx**
This PR runs https://github.com/akx/codemod-unittest-to-pytest-asserts to rewrite Unittest `self.assert...` assertions as plain assertions that can be introspected by Pytest's [assert rewriting](https://docs.pytest.org/en/7.1.x/how-to/assert.html).

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Hi @akx 
Thanks for your contribution ! 
few tests are failing with:
```bash
FAILED tests/test_core.py::CoreTester::test_masked_whiten - TypeError: type Tensor doesn't define __round__ method
```
I think adding `.item()` on those would fix the tests - could you please have a look? 🙏

**Review by younesbelkada — COMMENTED** [review]
Sorry for the additional iteration @akx ! Could you also fix
```bash
FAILED tests/test_reward_trainer.py::RewardTrainerTester::test_reward_trainer_margin
```
? 🙏 Thanks !

**Comment by akx** [comment]
Should be good to go again, I gave the failing test a spin locally (which took some editing because the tests don't run OOTB on `mps` devices, but there we go). 👍

**Comment by younesbelkada** [comment]
Thanks very much @akx - just re-ran the CI

**Review by younesbelkada — APPROVED** [review]
Huge work ! Thanks !

**Pull request merged**
