### PR TITLE
Small fixes to the PPO trainer doc and script.

### PR DESCRIPTION
**Pull request by namin**
One outstanding issue is that ppo_trainer.save_model doesn't exist. How do we actually save the model after training?

### CODE REVIEW

**Comment by lvwerra** [comment]
Hi @namin, thanks for the PR. However, I don't quite understand why the fixes are needed and what the changes fix exactly besides the typo in the docs. Can you elaborate?

**Comment by namin** [comment]
Sorry, I thought I needed these changes to get the script working, but maybe it was before installing from main instead of release. I reverted those changes, and kept only the doc changes.

Thank you!

**Review by younesbelkada — APPROVED** [review]
The changes look great to me, thanks!

**Comment by namin** [comment]
Thank you. I still have a lingering question about saving the model. The doc says to use `save_model` but this method is not available on the PPO Trainer. So looking at the source code, I use `_save_pretrained`, but that is an internal method. WDYT? Should the PPO Trainer expose `save_model`?

**Comment by lvwerra** [comment]
The `PPOTrainer` inherits from the `PyTorchModelHubMixin` and as such has a `save_pretrained` method by default that makes use of the private `_save_pretrained` method:

```python
    >>> import torch
    >>> import torch.nn as nn
    >>> from huggingface_hub import PyTorchModelHubMixin


    >>> class MyModel(nn.Module, PyTorchModelHubMixin):
    ...     def __init__(self):
    ...         super().__init__()
    ...         self.param = nn.Parameter(torch.rand(3, 4))
    ...         self.linear = nn.Linear(4, 5)

    ...     def forward(self, x):
    ...         return self.linear(x + self.param)
    >>> model = MyModel()

    # Save model weights to local directory
    >>> model.save_pretrained("my-awesome-model")
```

**Pull request merged**
