### PR TITLE
Clean examples

### PR DESCRIPTION
**Pull request by qgallouedec**
- Remove redundant `peft_config`
- Use `image.thumbnail` instead of re-implementing it

### CODE REVIEW

**Review by kashif — APPROVED** [review]

**Review by vwxyzjn — COMMENTED** [review]
cpo.py:
```
peft_config=get_peft_config(model_config),
```

dpo.py
```
peft_config=peft_config,
```

**Comment by qgallouedec** [comment]
Yes, it's because in some cases you need to know if the `peft_config` is None before instantiating the trainer:

```python
peft_config = get_peft_config(model_config)
if peft_config is not None:
    ...

trainer = DPOTrainer(
    ...
    peft_config=peft_config,
)
```

and sometime you don't need peft config until the trainer is instantiated (like in cpo):


```python
trainer = DPOTrainer(
    ...
    peft_config=get_peft_config(model_config),
)
```

For uniformity's sake, we could set the `peft_config` systematically before instantiating the trainer, but I find that a little less readable. But it's a detail and I'm fine with the solution.

**Comment by vwxyzjn** [comment]
I see. Either way make sense to me then. Feel free to choose either one and merge :)

**Comment by qgallouedec** [comment]
I would keep it like this. Thanks for the review. Can a maintainer merge? I can't.

**Pull request merged**
