### PR TITLE
change the `process` function in the example of DPO

### PR DESCRIPTION
**Pull request by AIR-hl**
#1752 #1541

### CODE REVIEW

**Comment by younesbelkada** [comment]
cc @kashif

**Review by kashif — APPROVED** [review]
thanks! nice catch

**Comment by AIR-hl** [comment]
> thanks! nice catch

@kashif Hi! I just modify the codes of dpo example, but there seems to be an error related to sft in checks
image

**Comment by vwxyzjn** [comment]
LGTM.

**Pull request merged**
