### PR TITLE
correct formatting of star sign in kto_trainer.mdx

### PR DESCRIPTION
**Pull request by mattany**
The "*" symbol in markdown doesn't show. I changed it to $\times$ so the mathematical formula is clearer

# What does this PR do?
correct formatting of star sign in kto_trainer.mdx

Fixes # (issue)

## Before submitting
- [X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by qgallouedec** [comment]
Thanks for the PR
It does not render as expected though.

image

I think you need to use `\\(\\times\\)`

**Comment by mattany** [comment]
@qgallouedec Thank you your comment! Sorry about that, this is my first time contributing. Only now I see the message from the bot. I will make corrections now until the rendered docs display correctly.

**Comment by qgallouedec** [comment]
No worry, actually you need me to approve the CI to run so that the doc builds, that's why it just appeared. Let's wait too see if your modification give the expected result

**Comment by qgallouedec** [comment]
Arf, still not. Try with `\\(\times\\)`

**Comment by mattany** [comment]
> Arf, still not. Try with `\\(\times\\)`

done. By the way, is there a reference somewhere to the version of markdown that is used on hf?

**Comment by kashif** [comment]
@mattany see here https://github.com/huggingface/doc-builder/blob/ea8aa6ef5d22c6f9508e40504c664bb5305674ff/kit/preprocessors/mdsvex/index.js#L47-L69

**Comment by qgallouedec** [comment]
Lgtm now! image
Thanks @mattany!

**Review by qgallouedec — APPROVED** [review]

**Pull request merged**
