### PR TITLE
setup_chat_format: throw error if there is already a template in base model

### PR DESCRIPTION
**Pull request by ngxson**
# What does this PR do?

Hi TRL team,

The context for this PR is from https://github.com/ggerganov/llama.cpp/pull/9778 . The user called `setup_chat_format` on base model `Llama-3.2-3B-Instruct`, which already has the llama-3.2 chat template. This will result in sub-optimal end result.

I believe it will be better to throw an error here, so that we don't overwrite chat template of the base model.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/trl/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a GitHub issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).
- [ ] Did you write any new necessary tests?

## Who can review?

(feel free to edit this part)

### CODE REVIEW

**Comment by qgallouedec** [comment]
Thanks for the PR! Can you just run `make precommit`

**Comment by ngxson** [comment]
@qgallouedec Thanks! Should be good now

**Comment by qgallouedec** [comment]
It seems like this case occurs twice in our tests:

```
FAILED tests/test_dataset_formatting.py::SetupChatFormatTestCase::test_example_with_setup_model - ValueError: Chat template is already added to the tokenizer. If you want to overwrite it, please set it to None
FAILED tests/test_dataset_formatting.py::SetupChatFormatTestCase::test_setup_chat_format - ValueError: Chat template is already added to the tokenizer. If you want to overwrite it, please set it to None
```


Can you update the example so that they use this function correctly?

**Comment by qgallouedec** [comment]
Lgtm, thanks @ngxson

**Comment by ngxson** [comment]
Thanks! I don't have merge permission, so please merge when you want 🤗

**Pull request merged**
