### PR TITLE
Bump liger-kernel to 0.4.0

### PR DESCRIPTION
**Pull request by ByronHsu**
This fixes HF grad acc and other fixes/features/optimizations

### CODE REVIEW

**Review by kashif — APPROVED** [review]

**Comment by qgallouedec** [comment]
As far as I understand, the grad accum think is only an issue with SFT right?

**Comment by kashif** [comment]
right i think its more about the updated kernels

**Comment by ByronHsu** [comment]
Yes grad accum is only used for sft. Besides grad accum, we also have other fixes.

**Comment by qgallouedec** [comment]
I approve, as this is an important issue affecting the most widely used trainer. (Thanks for solving it!)

For the record, generally speaking, I won’t raise the minimum version requirement unless a new feature from the dependency is needed in our codebase.

**Review by qgallouedec — APPROVED** [review]

**Pull request merged**
