### PR TITLE
[Feature] Add Ascend NPU accelerator support 

### PR DESCRIPTION
**Pull request by statelesshz**
### What does this PR do?
Since npu already supports Transformer/Accelerate and Peft out of the box, this would be a good addition to run TRL out of the box on npu.

cc @younesbelkada and @lvwerra

### CODE REVIEW

**Comment by statelesshz** [comment]
@younesbelkada @lvwerra I tried using `dpo.py` to do a sanity check on ascend [npu,](url) here is the training log: https://gist.github.com/statelesshz/4437ccec89c8f0d9df11444e8ca578cd

**Review by younesbelkada — COMMENTED** [review]
Looks great thank you very much for adding the NPU support! can you run the styling checks? `make precommit`

**Comment by statelesshz** [comment]
@younesbelkada Thanks for your reminder. CI is green:)

**Review by younesbelkada — APPROVED** [review]
Looks great!

**Pull request merged**
