### PR TITLE
fix: improve error message when `pad_token_id` is not configured

### LINKED ISSUE #1149: Suggestion (DPO): throw an error/warn if `tokenizer.pad_token` is `None`
## Description

trl/trainer/utils.py uses `tokenizer.pad_token` to pad the input sequence. 

This is problematic when `tokenizer.pad_token` is `None`, which results in a rather cryptic `TypeError`:

https://github.com/huggingface/trl/blob/911d3658e23786740c29b8042474bc05ce20b466/trl/trainer/utils.py#L314-L315

https://github.com/huggingface/trl/blob/911d3658e23786740c29b8042474bc05ce20b466/trl/trainer/utils.py#L323

```
...

[/usr/local/lib/python3.10/dist-packages/trl/trainer/utils.py](https://localhost:8080/#) in __call__(self, features)
    320                         raise ValueError(f"Unexpected key in batch '{k}'")
    321 
--> 322                     padded_batch[k] = pad_sequence(to_pad, batch_first=True, padding_value=padding_value)
    323                     # for the prompt, flip back so padding is on left side
    324                     if "prompt" in k:

[/usr/local/lib/python3.10/dist-packages/torch/nn/utils/rnn.py](https://localhost:8080/#) in pad_sequence(sequences, batch_first, padding_value)
    398     # assuming trailing dimensions and type of all the Tensors
    399     # in sequences are same and fetching those from sequences[0]
--> 400     return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
    401 
    402

TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
```

Perhaps checking whether `tokenizer.pad_token == None` beforehand and raising an error would help users debug the issue.

Any thoughts on this suggestion? Thanks!

### PR DESCRIPTION
**Pull request by yumemio**
## Description

Fixes #1149. Improves the error message when `tokenizer.pad_token` is `None` by providing the cause of the error and suggesting the next step to take.

## Current behaviour (before the PR)

```python
> tokenizer = AutoTokenizer.from_pretrained(...)
> print(tokenizer.pad_token)
None

> dpo_trainer = DPOTrainer(...)
> dpo_trainer.train()
...
TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
```

## New behaviour (after the PR)

```python
> tokenizer = AutoTokenizer.from_pretrained(...)
> print(tokenizer.pad_token)
None

> dpo_trainer = DPOTrainer(...)
> dpo_trainer.train()
...
ValueError: Padding is enabled, but the tokenizer is not configured with a padding token. Explicitly set `tokenizer.pad_token` (e.g. `tokenizer.pad_token = tokenizer.eos_token`) before calling the trainer.
```

Thanks in advance!

### CODE REVIEW

**Review by lvwerra — COMMENTED** [review]
Looks good to me, thanks for adding. Would you mind adding a test to check the desired behaviour?

**Review by younesbelkada — COMMENTED** [review]
Thanks ! Can you run the styling checks? `make precommit`

**Comment by yumemio** [comment]
Sorry for the lack of response - I have been busy lately. I will fix the styling issue and add relevant unit tests by the end of the week. Thanks for the patience! 🙏

**Comment by yumemio** [comment]
@lvwerra @younesbelkada Thanks for the feedback! I've fixed lint issues and added a test. Would you mind reviewing the code?

**Review by lvwerra — APPROVED** [review]

**Review by younesbelkada — APPROVED** [review]
Thanks!

**Comment by yumemio** [comment]
Thank you very much for reviewing!

**Pull request merged**
